services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://bdelgadomunoz:brayan2321@restaurant.tejv2ny.mongodb.net/PruebaOptimalTechnology?retryWrites=true&w=majority&appName=restaurant
    volumes:
      - .:/app 
    restart: unless-stopped 

networks:
  default:
    driver: bridge
